spring.application.name=mora-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/mora_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Swagger / OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Supabase Configuration
supabase.url=https://hurzbbckkdlnurekcvbb.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1cnpiYmNra2RsbnVyZWtjdmJiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4MTUxMDI5OCwiZXhwIjoyMDk3MDg2Mjk4fQ.tF33VEHVSuW3ZmVwow1xSLdjhvNjaICDfnVEiA-I1hw
supabase.bucket=mora-documents

# Multipart Configuration
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
